name: intl_translation
version: 0.16.0
author: Dart Team <misc@dartlang.org>
description: Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
homepage: https://github.com/dart-lang/intl_translation
environment:
  sdk: '>=1.12.0 <2.0.0'
documentation: http://www.dartdocs.org/documentation/intl_translation/latest
dependencies:
  analyzer: '>=0.29.1 <0.31.0'
  args: '>=0.12.1 <0.14.0'
  barback: ^0.15.2
  dart_style: ^1.0.0
  intl: '>=0.13.0 <0.16.0'
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=1.1.3 <2.0.0'
dev_dependencies:
  test: '>=0.10.0 <0.13.0'
transformers:
- $dart2js:
    $exclude:
    - test/message_extraction/embedded_plural_text_after_test.dart
    - test/message_extraction/embedded_plural_text_before_test.dart
    - test/message_extraction/examples_parsing_test.dart
    - test/message_extraction/failed_extraction_test.dart
    - test/message_extraction/make_hardcoded_translation.dart
    - test/message_extraction/message_extraction_no_deferred_test.dart
    - test/message_extraction/message_extraction_test.dart
    - test/message_extraction/really_fail_extraction_test.dart
- intl_translation:
    $include:
    - test/messages_with_transformer/transformer_test.dart
