name: intl_translation
version: 0.18.0
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.
repository: https://github.com/dart-lang/intl_translation

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  args: ^2.0.0
  dart_style: ^2.0.0
  intl: ^0.17.0
  path: ^1.0.0

dev_dependencies:
  lints: '>=1.0.0 <3.0.0'
  test: ^1.0.0
